### ISSUE TITLE
Cancel and Save in Customize have no effect

### ISSUE THREAD

**Issue by michael-k** [OpenBeerMap/OpenBeerMap.github.io#40]
On http://nlehuby.github.io/ there's no difference between clicking `Save` or `Cancel` when in `Customize` (Display settings).

**Comment by nlehuby** [comment]
Good and funny one ! Thanks.
The buttons don't have exactly the same effect : the Save button refreshes the list of the beers you can display on the map in the control and the list of the beers suggested in the edit bar modal.
And the behaviour of the Cancel button is quite irrelevant...

**Comment by michael-k** [comment]
So I guess this is the reason for #41.

I think there should only be an Close button and the refreshing must be done in any case.
