### ISSUE TITLE
Uncaught SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by CloCkWeRX** [OpenBeerMap/OpenBeerMap.github.io#51]
```
function display_restaurant(display = true)
```
Isn't particularly liked by chrome (45.0.2454.78 (Official Build) beta (64-bit))

http://stackoverflow.com/questions/894860/set-a-default-parameter-value-for-a-javascript-function

Introduced in a9c704908aa94a73d4df42cd75b3c894926c7885

**Comment by nlehuby** [comment]
Please test back on the dev server : http://nlehuby.github.io

**Comment by CloCkWeRX** [comment]
Specific error seems fixed there.
