### ISSUE TITLE
TypeError: e.center is undefined

### ISSUE THREAD

**Issue by CloCkWeRX** [OpenBeerMap/OpenBeerMap.github.io#53]
Firefox 40.0.3, first load of url results in 
```
TypeError: e.center is undefined
```
presumably just after I've granted location permission for the first time.

Offending extract appears to be:
```
var pos = new L.LatLng(e.center.lat, e.center.lon);
```

![broken](https://cloud.githubusercontent.com/assets/365751/9980789/073a3134-5fe5-11e5-83b9-c45bc7a4b9b9.png)

**Comment by nlehuby** [comment]
Thanks for your feedback.

This is unrelated with the user geolocation permission. 
It's an issue in the Overpass API json parsing.
