### ISSUE TITLE
User positioning not wired up fully

### ISSUE THREAD

**Issue by CloCkWeRX** [OpenBeerMap/OpenBeerMap.github.io#54]
We're doing:
```
/*User Location*/
map.locate({setView: false, enableHighAccuracy: true, locate: true, maximumAge: 60000,timeout: 8000 })
.on('locationfound', function(e){
    console.log("User positioning successful");
})
.on('locationerror', function(e){
    //console.log(e);
    console.log("ERROR: cannot get user position");
});
```

From the docs:

Tries to locate the user using the Geolocation API, firing a locationfound event with location data on success or a locationerror event on failure, and optionally sets the map view to the user's location with respect to detection accuracy (or to the world view if geolocation failed). See Locate options for more details.

setView	Boolean	If true, automatically sets the map view to the user location with respect to detection accuracy, or to world view if geolocation failed.

We should probably set that to true, at least for production.

**Comment by nlehuby** [comment]
Nope, because of the hash feature, that allows to share a position in the website.

If I send you this link : http://openbeermap.github.io/#16/51.9010/-8.4734
I expect you to see the bars around the geoloc (51.9010;-8.4734)

If the setview is active, you will only see the bars around your position.
