### ISSUE TITLE
Geolocation on boot isn't working on firefox

### ISSUE THREAD

**Issue by tassoman** [OpenBeerMap/OpenBeerMap.github.io#57]
Hello there, my Firefox's geolocation is «ask» by default. When I allow geolocation on loading the page it doesn't work asking again permission.

After allowing for the second time I get correctly geolocalized only by clicking on marker button.

Would be fine to reload the entire page on first geolocation confirmation.

**Comment by nlehuby** [comment]
Hi tassoman,

It's not a bug, it's a feature ! (see #54) 

The "geolocation on boot" is only to warm up the GPS, it does not change the position on the map.
If the map is centered on the user position, you cannot share a OpenBeerMap link anymore (http://openbeermap.github.io/#16/51.9010/-8.4734)

**Comment by tassoman** [comment]
Ok! I understand :)
Maybe we can integrate a «refresh position» button and a «share view» button ?

**Comment by nlehuby** [comment]
The "share view" is a good idea :+1:

**Comment by tassoman** [comment]
Thank you! :top:
