### ISSUE TITLE
Norwegian translation not loading, defaulting to French

### ISSUE THREAD

**Issue by FredrikLindseth** [OpenBeerMap/OpenBeerMap.github.io#60]
Im not sure what causes this, but if your browsers locale is set to Norwegian (NO) OpenBeerMap is set to french, which I assume is the default. 
Any ideas? Is the l20n-translation file broken?

**Comment by nlehuby** [comment]
You're right ! 
we forgot to update the locales manifest.json to tell the Norwegian is available !

**Comment by nlehuby** [comment]
fixed by #62
