### ISSUE TITLE
Some amenity=pub objects don't show up

### ISSUE THREAD

**Issue by CdRom1** [OpenBeerMap/OpenBeerMap.github.io#72]
Hi,

I'm just a new user of openbeermap (I haven't read the code). When I looked up my favourite street in Compiègne, I was surprised not to find my favourite bars!

A simple example: here's a screenshot from openstreetmap:
![image](https://user-images.githubusercontent.com/18699331/58871119-b9787480-86c1-11e9-9199-201f943df450.png)

And a screen from openbeermap:
![image](https://user-images.githubusercontent.com/18699331/58871194-e036ab00-86c1-11e9-8a4c-e90e3316dee1.png)

Actually, there is no bar from Compiègne popping up, at all.

Is this a bug, or is it related to specific policies on dropping some bars? If it's a bug, I would be happy to investigate on it, and fix it :)

**Comment by nlehuby** [comment]
Hi :)
thanks for your feedback !

This pub should be displayed. Actually, I can't reproduce your bug:
![image](https://user-images.githubusercontent.com/919962/58933488-b5069700-8767-11e9-81aa-44f80798c317.png)
http://openbeermap.github.io/#18/49.41564/2.82841

**Comment by CdRom1** [comment]
Me neither! But last time I tried to investigate, I had seen some ssl warnings in the logs. I guess it's not linked to the code, but to some temporary server-side misconfigurations.
